### ISSUE TITLE
Build is broken

### ISSUE THREAD

**Issue by jaredwolff** [hermitcore/rusty-demo#3]
Similar issue to what was seen [here.](https://github.com/hermitcore/rusty-hermit/issues/108) Looks like **compiler-builtins-asm** was removed from nightly.

**Comment by jaredwolff** [comment]
While this demo does not build, the instructions in the [rusty-hermit readme](https://github.com/hermitcore/rusty-hermit) work a-ok.

**Comment by stlankes** [comment]
Yes, I fixed it with my latest commit.

**Comment by stlankes** [comment]
Ok, I will close this issue.
